### ISSUE TITLE
Bad data point

### ISSUE THREAD

**Issue by tmairegasnighto** [davidteter/OPEN-RISOP#2]
The following data points in 0.93 is marked with the wrong state....

75200,OMT,MILITARY BASES,NEVADA ARNG FLOYD EDSALL TRAINING CENTER,1,,US,CLARK,NY,36.29092,-115.04126,"2,103",1.4,09P0,12P0,20220201,DMT,,    (Should be NV)   Seems to also be off by about a mile.

42600,ECON,ELECTRICAL SUBSTATIONS,ELECTRICAL SUBSTATION MOUNT HOLLY,20,LINKAGE,US,GASTON,NY,35.35955,-80.97456,669,0.15,14Q7,18Q7,20220202,DMT,,   (Should be NC)   

33.88196,-117.9565,RAYTHEON FULLERTON CA, ... CT,...   (Should be CA, not CT)

...note: I've only checked the northeast states.

**Comment by davidteter** [comment]
Hi! Much appreciated. I will fix this and upload the corrections today.
